set-option -g history-limit 4096
set-option -g status-position top
set-option -g detach-on-destroy on
unbind-key -a

set -g status-left ""
set -g status-right ""
set -g status-justify centre
set -g prefix C-space
set -g mouse on
set -g base-index 1
set -g renumber-windows on

bind -n C-r source-file ~/.tmux.conf

bind -n C-t new-window
bind -n C-w kill-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n C-d detach-client
bind c command-prompt
