monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@65
    position = 0x0
    transform = 0
    scale = 1
    bitdepth = 8
    cm = srgb
    supports_hdr = 0
}

monitorv2 {
    output = eDP-1
    mode = 1920x1080@65
    position = 0x1080
    transform = 0
    scale = 1
    bitdepth = 8
    cm = srgb
    supports_hdr = 0
}
