general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 2500
}

auth {
    fingerprint:enabled = true
}

background {
    path = screenshot
    brightness = 0.75
    blur_passes = 4
    blur_size = 8
}

label {
    monitor = HDMI-A-1
    text = cmd[update:1000] date +"%I:%M:%S %p"
    color = rgb(ffffff)
    font_size = 64
    font_family = Ubuntu Nerd Font Bold
    position = 0, 72
}

label {
    monitor = HDMI-A-1
    text = Welcome Back, $USER!
    color = rgb(ffffff)
    font_size = 28
    font_family = UbuntuMono Nerd Font Bold
    position = 0, 0
}

input-field {
    monitor = HDMI-A-1
    size = 384, 48
    placeholder_text =
    dots_size = 0.33
    dots_spacing = 0.25
    outline_thickness = 3
    fade_on_empty = false

    inner_color = rgba(00000066)
    outer_color = rgb(ffbf00)
    check_color = rgb(30cbff)
    fail_color = rgb(ef2f2f)
    font_color = rgb(ffffff)

    position = 0, -72
}
