background = 0xFF000000
base = 0xFF171717
text = 0xFFDFDFDF
alternate_base = 0xFF0B0B0B
bright_text = 0xFFFFFF
accent = 0xFFFFBF00
accent_secondary = 0xFF3DAEE9
font-size = 13
small_font_size = 11
font_family = Ubuntu Bold
font_family_monospace = Ubuntu Mono Bold
