[window]
padding = { x = 16, y = 16 }
dynamic_title = true

[scrolling]
history = 4096

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session"]

[font]
normal = { family = "UbuntuMono Nerd Font", style = "regular" }
size = 17

[colors.primary]
foreground = "#ffffff"
background = "#000000"
dim_foreground = "#dfdfdf"
bright_foreground = "#171717"

[colors.normal]
black = "#404040"
red = "#ff0040"
green = "#40ff00"
yellow = "#ffbf00"
blue = "#0040ff"
magenta = "#bf00ff"
cyan = "#00ffbf"
white = "#bfbfbf"

[colors.bright]
black = "#616161"
red = "#ff547f"
green = "#7fff54"
yellow = "#ffd454"
blue = "#547fff"
magenta = "#d454ff"
cyan = "#54ffd4"
white = "#e0e0e0"

[colors.dim]
black = "#212121"
red = "#bf002f"
green = "#2fbf00"
yellow = "#bf8f00"
blue = "#002fbf"
magenta = "#8f00bf"
cyan = "#00bf8f"
white = "#a1a1a1"
