[Resolve]
DNS=100.100.100.100 2a07:a8c0::#435e9d.dns.nextdns.io 45.90.28.0#435e9d.dns.nextdns.io 2606:4700:4700::1111#one.one.one.one 1.1.1.1#one.one.one.one
FallbackDNS=2a07:a8c1::#435e9d.dns.nextdns.io 45.90.30.0#435e9d.dns.nextdns.io 2606:4700:4700::1001#one.one.one.one 1.0.0.1#one.one.one.one
#DNS=2606:4700:4700::1111#one.one.one.one 1.1.1.1#one.one.one.one
#FallbaskDNS=2606:4700:4700::1001#one.one.one.one 1.0.0.1#one.one.one.one
DNSOverTLS=yes
Domains=~ts.net
DNSSEC=allow-downgrade
MulticastDNS=yes
LLMNR=yes
Cache=yes
CacheFromLocalhost=yes
DNSStubListener=yes
ReadEtcHosts=yes
ResolveUnicastSingleLabel=no
StaleRetentionSec=0
